version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: simple-crud-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"  # Map to port 3307 to avoid conflict with local MySQL
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simple_crud_db
      MYSQL_USER: simple_crud
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - simple-crud-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: simple-crud-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - simple-crud-network

volumes:
  mysql_data:
    driver: local

networks:
  simple-crud-network:
    driver: bridge
